### ISSUE TITLE
Our Services

### ISSUE THREAD

**Issue by VinodBangalore** [AmithRajMP/AgileIDC#10]
Point 1: Replace Oracle Consulting to Software Consulting. 
Point 2: Replace Managed Services with Business Process Management (BPO). 
Write up : Retain Same Image
![agiles 1](https://user-images.githubusercontent.com/34021124/33255371-f3c96eba-d398-11e7-89e7-bc6d27404a6d.jpg)

Agiles Australia provides unparalleled integrated range of Offshore and Onsite Business process management support that accelerate innovations. Our company acts as an extension of your business to help:
•	Transforms Business Processes
•	Optimizes Costs
•	Creates Value Teams offshore 
Point 3: Please Justify Paragraph across the website

**Comment by AmithRajMP** [comment]
All the issues are taken care of. 
Point 3 is also taken care of everywhere, except for some places where justify is intentionally removed and made to display the text in a centralized indentation.
Feel free to reopen the issue if not updated in the website within this week.
