### ISSUE TITLE
Our Values

### ISSUE THREAD

**Issue by VinodBangalore** [AmithRajMP/AgileIDC#12]
Point 1: The image needs to be reset to original size, seems compressed, elongated currently

**Comment by AmithRajMP** [comment]
Will fix this issue along with issue 13. 
This issue is understood. 
I will also make it responsive for other devices

**Comment by VinodBangalore** [comment]
Great Amith.

**Comment by AmithRajMP** [comment]
Thanks @Hiddenx for fixing this issue
