### ISSUE TITLE
Careers

### ISSUE THREAD

**Issue by VinodBangalore** [AmithRajMP/AgileIDC#13]
Point 1: Need to bring both heading and content under same banner, color 
Point 2: Change Colour of send email to  suitable colour. 
Contact Us: 
Expand the Blue color banner to entire page, change color

**Comment by AmithRajMP** [comment]
Point 1 is still pending.  Will change the image and give a whitish tinge to it and then change the text color to Black
Point 2 is fixed .
Explain Contact Us part with more detail.
Revert Back @VinodBangalore

**Comment by VinodBangalore** [comment]
Amith,
I had a very detailed thought on the Contact Us page, considering the page branches out of "contact info" Could we just add the same info on Agileidc website to extreme right (next to Contact info) or try this if possible. 
![contact us](https://user-images.githubusercontent.com/34021124/33349378-85b7630c-d4e5-11e7-818e-7e42fe091d32.jpg)

**Comment by AmithRajMP** [comment]
I have made it look beautiful and now it doesnt look like google forms at all
