### ISSUE TITLE
Scroll In as we view pages

### ISSUE THREAD

**Issue by VinodBangalore** [AmithRajMP/AgileIDC#14]
Amith,
I just observed on AgileIdc website, we we move from one section to another the new section appears like in the powerpoint ppt zoom in. Our website content is stagnant. Do you think its possible to recreate the same on our website? It gives a polished look. 

Does it involve too much of work? I could call you to explain.

**Comment by AmithRajMP** [comment]
Only Smooth Scroll is pending , rest all is taken care of.
Actually the effects require a lot of work.

**Comment by AmithRajMP** [comment]
Thanks @Hiddenx . The issue is fixed
