### ISSUE TITLE
Headers Scrolling

### ISSUE THREAD

**Issue by VinodBangalore** [AmithRajMP/AgileIDC#15]
When we click on Headers / Tab on top right, the landing page does not display the respective name. I believe this is because of the sticker header now lowering down on each section. 

Ex: When I click on Products, It goes to the product section but name Products is not visible. Attached image

![image](https://user-images.githubusercontent.com/34021124/33642016-b785f594-da83-11e7-99d4-9635306c58ec.png)

**Comment by AmithRajMP** [comment]
The issue is fixed.
