### ISSUE TITLE
Products Hyperlink

### ISSUE THREAD

**Issue by VinodBangalore** [AmithRajMP/AgileIDC#16]
When you click on each product it moves to homepage, it should be moving to expanded version of the particular product. 

Ex: When I hover my mouse  on SAYARA - Dealer Management System, it gets highlighted. When you click on the name it goes to homepage. Can we direct that to detailed info page of that product(After they read more).

**Comment by AmithRajMP** [comment]
This issue is also fixed. Regarding a new product page for all the products, only sayara has it.
