### ISSUE TITLE
Homepage Banner

### ISSUE THREAD

**Issue by VinodBangalore** [AmithRajMP/AgileIDC#7]
Minimize the Banner in the backdround to fit the screen. Currently, partial text is visible and the user cannot view the slide option (dots suggesting next slideover option).
Point 1. No Spacing is followed for headings in all slides except for 1st slide (Wondering what we do at Agiles Consulting). Space after developers, creators.
Point 2. nimble (N capital please) in slide 4.
Point 3. Focus and relationship: IT Consulting, Software development and Business Process Management

**Comment by AmithRajMP** [comment]
Only Minimizing the size of the banner is left. All the other points are taken care of.

**Comment by AmithRajMP** [comment]
This issue is closed , will reflect in the website shortly

**Comment by AmithRajMP** [comment]
Thanks @Hiddenx
