### ISSUE TITLE
Hyperlinking Tabs on right extreme corner to respective pages

### ISSUE THREAD

**Issue by VinodBangalore** [AmithRajMP/AgileIDC#8]
Point 1: Hyperlinking Tabs on right extreme corner to respective pages.
Point 2:  Freezing the top pane to stay on top as we scroll down the page. Will enable people to click on logo / tabs to go to res page.

**Comment by AmithRajMP** [comment]
Point 1 is fixed for Mozilla Firefox browser while in Chrome browser the scroll is not smooth: will be fixed shortly.
Point 2 is not yet fixed. Will be fixed shortly.

**Comment by AmithRajMP** [comment]
Point 2 is still pending . Point 1 is fixed

**Comment by AmithRajMP** [comment]
@Hiddenx look into this part.
Sticky Header

**Comment by AmithRajMP** [comment]
Thanks @Hiddenx . The issue is fixed
