### ISSUE TITLE
Re-arranging the content and colour co-ordination

### ISSUE THREAD

**Issue by VinodBangalore** [AmithRajMP/AgileIDC#9]
Point 1: Could you please create a colour code for alternate sections. Ex: White and Grey as in Agileidc.com
Point 2: Re-arrange the sections in the following order. 
Homepage
Our Products
Our Services 
Our Values
Recommandations
Careers
Contact Us

**Comment by AmithRajMP** [comment]
Point 1 will be taken care of shortly.
Point 2 can be done if there is more clarity on "Recommendations" 
This was not mentioned . 
Please revert @VinodBangalore

**Comment by VinodBangalore** [comment]
Amith,
I had just reworded testimonials as recommendations, sorry for the confusion. We have the testimonials on our page already.

**Comment by AmithRajMP** [comment]
This is taken care of issue is closed.
I have re arranged it in the given order.
